export const START_DOWNLOAD_MOVIES = "START_DOWNLOAD_MOVIES";
export const FINISH_DOWNLOAD_MOVIES = "FINISH_DOWNLOAD_MOVIES";
export const ERROR_DOWNLOAD_MOVIES = "ERROR_DOWNLOAD_MOVIES";

export const DESCRIPCION_MOVIE = "MOVIE_DESCRIPTION";